# Generated by Django 3.1.1 on 2020-10-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstage',
            name='image',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentstage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='studentstage',
            unique_together={('name', 'school')},
        ),
    ]
